# Generated by Django 5.1.4 on 2024-12-16 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonateInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donate_amt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sub_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('grand_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('zakat_year', models.IntegerField(choices=[(2023, 2023), (2024, 2024)], default=2024, verbose_name='year')),
                ('message', models.CharField(blank=True, max_length=200, null=True)),
                ('record_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('d_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donors', to='zapp.donors')),
            ],
            options={
                'verbose_name_plural': 'DONATE INFO',
            },
        ),
    ]
