# Generated by Django 5.1.4 on 2024-12-18 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0002_donateinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donateinfo',
            name='d_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giver', to='zapp.donors'),
        ),
    ]
