# Generated by Django 5.1.4 on 2024-12-19 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0003_alter_donateinfo_d_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='donateinfo',
            name='donation_type',
            field=models.CharField(choices=[('donation', 'Donation'), ('zakat', 'Zakat'), ('other', 'Other_purpose')], default='donation', max_length=50, null=True),
        ),
    ]
