# Generated by Django 5.1.4 on 2024-12-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0008_alter_donateinfo_donation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donateinfo',
            name='donation_type',
            field=models.CharField(choices=[('', '-- Select --'), ('donation', 'Donation'), ('zakat', 'Zakat'), ('other', 'Other_purpose')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ZakatRecipients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipients_name', models.CharField(blank=True, max_length=150)),
                ('recipients_address', models.CharField(blank=True, max_length=200, null=True)),
                ('zakat_money', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('recipients_mobile', models.CharField(max_length=20, null=True)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('recipients_category', models.CharField(choices=[('SPECIAL', 'special'), ('GENERAL', 'general')], default='general', max_length=50)),
                ('zakat_year', models.IntegerField(choices=[(2023, 2023), (2024, 2024)], default=2024, verbose_name='year')),
                ('zakat_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('donor_name', models.ManyToManyField(related_name='zakat_donor', to='zapp.donors')),
            ],
            options={
                'verbose_name_plural': 'ZAKAT RECIPIENTS',
            },
        ),
    ]
