# Generated by Django 5.1.4 on 2024-12-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0009_alter_donateinfo_donation_type_zakatrecipients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakatrecipients',
            name='recipients_mobile',
            field=models.CharField(max_length=20),
        ),
    ]
