# Generated by Django 5.1.4 on 2024-12-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0010_alter_zakatrecipients_recipients_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakatrecipients',
            name='donor_name',
            field=models.ManyToManyField(blank=True, null=True, related_name='zakat_donor', to='zapp.donors'),
        ),
        migrations.AlterField(
            model_name='zakatrecipients',
            name='recipients_mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
