# Generated by Django 5.1.4 on 2025-01-01 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0012_alter_zakatrecipients_recipients_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donateinfo',
            name='zakat_year',
            field=models.IntegerField(choices=[(2023, 2023), (2024, 2024), (2025, 2025)], default=2025, verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='zakatrecipients',
            name='zakat_year',
            field=models.IntegerField(choices=[(2023, 2023), (2024, 2024), (2025, 2025)], default=2025, verbose_name='year'),
        ),
    ]
