# Generated by Django 5.1.4 on 2025-01-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0013_alter_donateinfo_zakat_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakatrecipients',
            name='donor_name',
            field=models.ManyToManyField(blank=True, related_name='zakat_donor', to='zapp.donors'),
        ),
    ]
