# Generated by Django 5.1.4 on 2025-01-03 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0014_alter_zakatrecipients_donor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipientsArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipients_name', models.CharField(blank=True, max_length=150)),
                ('recipients_address', models.CharField(blank=True, max_length=200, null=True)),
                ('zakat_money', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('recipients_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('donor_name', models.CharField(blank=True, max_length=200)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('recipients_category', models.CharField(max_length=50)),
                ('zakat_year', models.IntegerField()),
                ('zakat_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
