# Generated by Django 5.1.4 on 2025-01-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0015_recipientsarchive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipientsarchive',
            old_name='created_at',
            new_name='archive_date',
        ),
        migrations.RemoveField(
            model_name='recipientsarchive',
            name='donor_name',
        ),
        migrations.RemoveField(
            model_name='recipientsarchive',
            name='zakat_date',
        ),
        migrations.RemoveField(
            model_name='zakatrecipients',
            name='zakat_date',
        ),
        migrations.AddField(
            model_name='recipientsarchive',
            name='donation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zakatrecipients',
            name='donation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
