# Generated by Django 5.1.4 on 2025-01-04 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0016_rename_created_at_recipientsarchive_archive_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zakatrecipients',
            name='donor_name',
        ),
        migrations.AddField(
            model_name='zakatrecipients',
            name='donor_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zapp.donors'),
        ),
    ]
