# Generated by Django 5.1.4 on 2025-01-19 15:30

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0018_alter_donors_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalZakatRecipients',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('recipients_name', models.CharField(blank=True, max_length=150)),
                ('recipients_address', models.CharField(blank=True, max_length=200, null=True)),
                ('zakat_money', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('recipients_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('recipients_category', models.CharField(choices=[('general', 'GENERAL'), ('special', 'SPECIAL')], default='general', max_length=50)),
                ('zakat_year', models.IntegerField(choices=[(2023, 2023), (2024, 2024), (2025, 2025)], default=2025, verbose_name='year')),
                ('donation_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('donor_name', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='zapp.donors')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical zakat recipients',
                'verbose_name_plural': 'historical ZAKAT RECIPIENTS',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
